print("Persona: ¡Hola, Michi!")
print("Gato: Miaw, miaw. ¿miaw?")
print("Persona: Si, vamos a desayunar, ¿cómo domiste?")
print("Gato: Miaw... miaw...miaw, miaw")
print("Persona: ¡Wow, quisiera ser un gato y dormir todo el dia! ¿Que haras hoy?")
print("Gato: Miaaaawwww.")
print("Persona: Bueno, entonces me voy a trabajar, Adios, Michi.")
print("Gato: *Lo ignora* Miaw...")